In [1]:
# Import the libraries we need for this lab

import torch 
import torch.nn as nn
from torch import sigmoid
import matplotlib.pylab as plt
import numpy as np
torch.manual_seed(0)

In [3]:
def plot_model(x, y, model, epoch, leg = True):
    plt.plot(x.numpy(), model(x).detach().numpy(), label = ('epoch ' + str(epoch)))
    plt.xlabel('x')
    if leg == True:
        plt.legend()
    else:
        pass

In [4]:
class Net(nn.Module):
    def __init__(self, input_l, hidden_l, output_l):
        super(Net, self).__init__()
        self.linear1 = nn.Linear(input_l, hidden_l)
        self.linear2 = nn.Linear(hidden_l, output_l)
        self.a1 = None
        self.l1 = None
        self.l2 = None
    def forward(self, x):
        self.l1 = self.linear1(x)
        self.a1 = sigmoid(self.l1)
        self.l2 = self.linear2(self.a1)
        y_hat = sigmoid(self.linear2(self.a1))
        return y_hat

In [20]:
# Define the training function

def train(Y, X, model, optimizer, criterion, epochs=1000):
    cost = []
    total=0
    for epoch in range(epochs):
        total=0
        for y, x in zip(Y, X):
            yhat = model(x)
            loss = criterion(yhat, y)
            loss.backward()
            optimizer.step()
            optimizer.zero_grad()
            #cumulative loss 
            total+=loss.item() 
        cost.append(total)
        if epoch % 300 == 0:    
            PlotStuff(X, Y, model, epoch, leg=True)
            plt.show()
            model(X)
            plt.scatter(model.a1.detach().numpy()[:, 0], model.a1.detach().numpy()[:, 1], c=Y.numpy().reshape(-1))
            plt.title('activations')
            plt.show()
    return cost

In [12]:
x = torch.arange(-20, 20, 1).view(-1, 1).type(torch.FloatTensor)
y = torch.zeros(x.shape[0])
y[(x[:, 0] > -4) & (x[:, 0] < 4)] = 1.0

In [13]:
def criterion_cross(outputs, labels):
    out = -1 * torch.mean(labels * torch.log(outputs) + (1 - labels) * torch.log(1 - outputs))
    return out

In [21]:
input_l = 1
hidden_l = 2
output_l = 1
learning_rate = 0.1
model = Net(input_l, hidden_l, output_l)
optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)
cost_cross = train(y, x, model, optimizer, criterion_cross, epochs = 1000)
plt.plot(cost_cross)
plt.xlabel('epoch')
plt.title('cross entropy loss')

RuntimeError: both arguments to matmul need to be at least 1D, but they are 0D and 2D

In [15]:
x = torch.tensor([0.0])
y_hat = model(x)
y_hat

tensor([0.2297], grad_fn=<SigmoidBackward>)

In [16]:
x_ = torch.tensor([[0.0], [2.0], [3.0]])
y_hat = model(x_)
y_hat

tensor([[0.2297],
        [0.2314],
        [0.2330]], grad_fn=<SigmoidBackward>)

In [17]:
y_hat = y_hat > 0.5
y_hat

tensor([[False],
        [False],
        [False]])

In [24]:
mse_loss = nn.MSELoss()
learning_rate = 0.1
model = Net(input_l, hidden_l, output_l)
optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)
cost_mse = train(y, x, model, optimizer, mse_loss, epochs = 1000)
plt.plot(cost_mse)
plt.xlabel('epoch')
plt.title('MSE loss')

RuntimeError: both arguments to matmul need to be at least 1D, but they are 0D and 2D