In [1]:
import torch 
import torch.nn as nn
import matplotlib.pyplot as plt
import numpy as np
from scipy import ndimage, misc

In [2]:
conv = nn.Conv2d(in_channels = 1, out_channels = 2, kernel_size = 3)
gx = torch.tensor([[1.0, 0, -1.0], [2.0, 0, -2.0], [1.0, 0, -1.0]])
conv.state_dict()['weight'][0][0] = gx
conv.state_dict()['bias'][0] = 0.0
conv.state_dict()

OrderedDict([('weight',
              tensor([[[[ 1.0000,  0.0000, -1.0000],
                        [ 2.0000,  0.0000, -2.0000],
                        [ 1.0000,  0.0000, -1.0000]]],
              
              
                      [[[-0.3054, -0.0110,  0.1854],
                        [-0.0390,  0.2923,  0.2066],
                        [-0.1858,  0.2571,  0.2828]]]])),
             ('bias', tensor([0.0000, 0.1470]))])

In [3]:
image = torch.zeros(1, 1, 5, 5)
image[0, 0, :, 2] = 1
image

tensor([[[[0., 0., 1., 0., 0.],
          [0., 0., 1., 0., 0.],
          [0., 0., 1., 0., 0.],
          [0., 0., 1., 0., 0.],
          [0., 0., 1., 0., 0.]]]])

In [4]:
z = conv(image)
z

tensor([[[[-4.0000,  0.0000,  4.0000],
          [-4.0000,  0.0000,  4.0000],
          [-4.0000,  0.0000,  4.0000]],

         [[ 0.8217,  0.6854, -0.3832],
          [ 0.8217,  0.6854, -0.3832],
          [ 0.8217,  0.6854, -0.3832]]]], grad_fn=<MkldnnConvolutionBackward>)

In [5]:
a = torch.relu(z)
a

tensor([[[[0.0000, 0.0000, 4.0000],
          [0.0000, 0.0000, 4.0000],
          [0.0000, 0.0000, 4.0000]],

         [[0.8217, 0.6854, 0.0000],
          [0.8217, 0.6854, 0.0000],
          [0.8217, 0.6854, 0.0000]]]], grad_fn=<ReluBackward0>)

In [6]:
relu = nn.ReLU()
relu(z)

tensor([[[[0.0000, 0.0000, 4.0000],
          [0.0000, 0.0000, 4.0000],
          [0.0000, 0.0000, 4.0000]],

         [[0.8217, 0.6854, 0.0000],
          [0.8217, 0.6854, 0.0000],
          [0.8217, 0.6854, 0.0000]]]], grad_fn=<ReluBackward0>)

In [7]:
image1 = torch.zeros(1, 1, 4, 4)
image1[0, 0, 0, :] = torch.tensor([1.0, 2.0, 3.0, -4.0])
image1[0, 0, 1, :] = torch.tensor([0.0 ,2.0, -3.0, 0.0])
image1[0, 0, 1, :] = torch.tensor([0., 2., 3., 1.])
image1

tensor([[[[ 1.,  2.,  3., -4.],
          [ 0.,  2.,  3.,  1.],
          [ 0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.]]]])