In [1]:
import torch 
import torch.nn as nn
import matplotlib.pyplot as plt
import numpy as np
from scipy import ndimage, misc

In [2]:
conv = nn.Conv2d(in_channels = 1, out_channels = 1, kernel_size = 3)
conv

Conv2d(1, 1, kernel_size=(3, 3), stride=(1, 1))

In [4]:
conv.state_dict()['weight'][0][0] = torch.tensor([[1.0, 0, -1.0], [2.0, 0, -2.0], [1.0, 0.0, -1.0]])
conv.state_dict()['bias'][0] = 0.0
conv.state_dict()

OrderedDict([('weight',
              tensor([[[[ 1.,  0., -1.],
                        [ 2.,  0., -2.],
                        [ 1.,  0., -1.]]]])),
             ('bias', tensor([0.]))])

In [5]:
image = torch.zeros(1, 1, 5, 5)
image[0, 0, :, 2] = 1
image

tensor([[[[0., 0., 1., 0., 0.],
          [0., 0., 1., 0., 0.],
          [0., 0., 1., 0., 0.],
          [0., 0., 1., 0., 0.],
          [0., 0., 1., 0., 0.]]]])

In [6]:
z = conv(image)
z

tensor([[[[-4.,  0.,  4.],
          [-4.,  0.,  4.],
          [-4.,  0.,  4.]]]], grad_fn=<MkldnnConvolutionBackward>)

In [7]:
k = 2
conv1 = nn.Conv2d(in_channels = 1, out_channels = 1, kernel_size = k)
conv1.state_dict()['weight'][0][0] = torch.tensor([[1.0, 1.0], [1.0, 1.0]])
conv1.state_dict()['bias'][0] = 0.0
conv1.state_dict()
conv1

Conv2d(1, 1, kernel_size=(2, 2), stride=(1, 1))

In [8]:
m = 4
image1 = torch.ones(1, 1, m, m)

In [9]:
z1 = conv1(image1)
z1, z1.shape[2:4]

(tensor([[[[4., 4., 4.],
           [4., 4., 4.],
           [4., 4., 4.]]]], grad_fn=<MkldnnConvolutionBackward>),
 torch.Size([3, 3]))

In [11]:
conv3 = nn.Conv2d(in_channels = 1, out_channels = 1, kernel_size = 2, stride = 2)
conv3.state_dict()['weight'][0][0] = torch.tensor([[1.0, 1.0], [1.0, 1.0]])
conv3.state_dict()['bias'][0] = 0.0
conv3.state_dict()

OrderedDict([('weight',
              tensor([[[[1., 1.],
                        [1., 1.]]]])),
             ('bias', tensor([0.]))])

In [12]:
z3 = conv3(image1)
z3, z3.shape[2:4]

(tensor([[[[4., 4.],
           [4., 4.]]]], grad_fn=<MkldnnConvolutionBackward>),
 torch.Size([2, 2]))

In [13]:
image1

tensor([[[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]])

In [15]:
conv4 = nn.Conv2d(in_channels = 1, out_channels = 1, kernel_size = 2, stride = 3)
conv4.state_dict()['weight'][0][0] = torch.tensor([[1.0, 1.0], [1.0, 1.0]])
conv4.state_dict()['bias'][0] = 0.0
conv4.state_dict()
z4 = conv4(image1)
z4, z4.shape[2:4]

(tensor([[[[4.]]]], grad_fn=<MkldnnConvolutionBackward>), torch.Size([1, 1]))

In [16]:
conv5 = nn.Conv2d(in_channels = 1, out_channels = 1, kernel_size = 2, stride = 3, padding = 1)
conv5.state_dict()['weight'][0][0] = torch.tensor([[1.0, 1.0], [1.0, 1.0]])
conv5.state_dict()['bias'][0] = 0.0
conv.state_dict()
z5 = conv5(image1)
z5, z4.shape[2:4]

(tensor([[[[1., 2.],
           [2., 4.]]]], grad_fn=<MkldnnConvolutionBackward>),
 torch.Size([1, 1]))

In [17]:
image = torch.randn((1, 1, 4, 4))
image

tensor([[[[-1.3767, -0.0040,  1.0667,  0.2048],
          [-0.0287, -0.9756, -0.0347, -0.9754],
          [-1.7278, -0.2694,  0.8425,  0.3524],
          [ 1.1588, -0.0125,  0.9309,  0.2482]]]])

In [ ]:
conv = nn.Conv2d(in_channels = 1, out_channels = 1, kernel_size = 3)
conv.state_dict()['weight'][0][0] = torch.tensor([[0, 0, 0], [0, 0, 0], [0, 0.0, 0]])
conv.state_dict()['bias'][0] = 0.0