In [1]:
import numpy as np
from scipy import sparse

In [3]:
a = np.random.randint(0, 2, 100000).reshape(100, 1000)
sparcity = 1.0 - (np.count_nonzero(a) /  a.size)
print(round(sparcity, 4))

0.4974


In [5]:
a = np.random.poisson(0.3, (10, 100))
b = sparse.coo_matrix(a)
c = b.todense()

print('a', type(a), a.shape, '\n', 'b', type(b), b.shape, '\n', 'c', type(c), c.shape, '\n')

a <class 'numpy.ndarray'> (10, 100) 
 b <class 'scipy.sparse.coo.coo_matrix'> (10, 100) 
 c <class 'numpy.matrix'> (10, 100) 



In [10]:
a = np.random.poisson(0.3, (10, 100))
b = sparse.csc_matrix(a)
print(b)

  (6, 0)	1
  (9, 0)	1
  (3, 1)	1
  (5, 1)	1
  (6, 1)	1
  (9, 1)	1
  (6, 2)	1
  (1, 3)	1
  (2, 3)	2
  (5, 3)	1
  (0, 4)	1
  (3, 4)	1
  (4, 4)	1
  (5, 5)	1
  (8, 5)	1
  (0, 6)	1
  (4, 6)	1
  (5, 6)	1
  (7, 6)	1
  (0, 7)	2
  (2, 7)	1
  (4, 7)	1
  (5, 7)	1
  (8, 7)	1
  (5, 8)	1
  :	:
  (0, 89)	1
  (9, 89)	1
  (6, 90)	1
  (0, 91)	1
  (3, 91)	2
  (6, 91)	1
  (8, 91)	1
  (2, 92)	1
  (5, 93)	2
  (0, 94)	1
  (3, 94)	1
  (5, 94)	1
  (7, 94)	1
  (6, 95)	1
  (9, 95)	2
  (4, 96)	1
  (5, 96)	1
  (8, 96)	1
  (9, 96)	1
  (2, 97)	1
  (3, 97)	1
  (0, 99)	1
  (1, 99)	1
  (2, 99)	2
  (3, 99)	1


In [11]:
a = np.random.poisson(0.3, (10, 100))
b = sparse.csr_matrix(a)
print(b)

  (0, 0)	1
  (0, 1)	1
  (0, 5)	2
  (0, 6)	1
  (0, 9)	1
  (0, 21)	1
  (0, 22)	1
  (0, 31)	1
  (0, 34)	3
  (0, 41)	2
  (0, 44)	1
  (0, 58)	1
  (0, 62)	1
  (0, 63)	1
  (0, 66)	1
  (0, 76)	1
  (0, 82)	1
  (0, 91)	1
  (0, 93)	1
  (0, 96)	1
  (0, 97)	1
  (1, 0)	1
  (1, 3)	1
  (1, 4)	1
  (1, 5)	1
  :	:
  (8, 89)	1
  (8, 90)	1
  (8, 96)	1
  (8, 99)	1
  (9, 1)	1
  (9, 6)	1
  (9, 20)	1
  (9, 21)	1
  (9, 23)	1
  (9, 24)	1
  (9, 28)	2
  (9, 32)	1
  (9, 33)	2
  (9, 34)	1
  (9, 37)	1
  (9, 45)	1
  (9, 48)	1
  (9, 53)	1
  (9, 59)	1
  (9, 67)	2
  (9, 71)	1
  (9, 79)	1
  (9, 80)	1
  (9, 81)	1
  (9, 98)	1


In [13]:
rows = [0, 1, 2, 8]
cols = [1, 0, 4, 8]
vals = [1, 2, 1, 4]

a = sparse.coo_matrix((vals, (rows, cols)))

In [14]:
print(b.todense())

[[1 1 0 0 0 2 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 3 0
  0 0 0 0 0 2 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 1 0 0 1 0 0 0 0 0
  0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 1 0 0 1 1 0 0]
 [1 0 0 1 1 1 0 0 0 0 0 1 0 0 0 0 2 0 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 1 0 0
  0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 1 1 0 0 1 0 0 0
  0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 1 1 0 0 0 2 1 1 1]
 [0 0 1 0 1 0 0 0 0 1 0 1 0 0 1 0 0 0 1 0 1 0 0 0 1 1 0 0 0 1 0 0 1 0 0 0
  2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 1 0 0 0 2 2 0 0 0 0 0
  1 0 0 1 1 0 0 1 0 1 0 1 0 0 0 0 0 0 1 0 1 0 1 0 1 0 0 0]
 [1 0 1 0 0 1 2 0 1 0 0 1 0 0 0 0 0 1 1 0 1 0 0 1 0 0 0 0 1 0 2 0 0 0 0 0
  0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 1 1 0
  0 0 0 1 1 0 0 1 0 1 0 1 2 0 0 0 0 1 0 1 2 1 0 0 0 0 0 0]
 [0 1 0 1 0 0 0 0 1 0 0 1 1 1 0 0 0 1 0 0 0 1 0 0 1 0 0 2 0 1 0 0 0 0 0 1
  1 0 0 0 0 0 0 0 0 0 1 0 1 1 0 0 1 0 2 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 2 0 

In [15]:
b = a.tocsr()

In [16]:
c = sparse.csr_matrix(np.array([0, 1, 0 ,0, 2, 0, 0, 0, 1]).reshape(1, 9))
print(b.shape, c.shape)
d = sparse.vstack([b, c])
print(d.todense())

(9, 9) (1, 9)
[[0 1 0 0 0 0 0 0 0]
 [2 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 4]
 [0 1 0 0 2 0 0 0 1]]


In [17]:
file_name = 'sparse_matrix.npz'
sparse.save_npz(file_name, d)
e = sparse.load_npz(file_name)
print(e.shape)

(10, 9)
